#!/usr/bin/env python
from fnmatch import fnmatch

print fnmatch("htmlcov","htmlcov*")
print fnmatch("htmlcov/index.html","htmlcov*")
print fnmatch("htmlcov/index.html","htmlcov*")
print fnmatch("app.egg-info/PKG-INFO","*.egg-info*")

print "\nlevel"
print fnmatch("/path1/path2/path3","/*/*/*")
print fnmatch("/path1/path2/path3","/*/*/*/*")
