#!/usr/bin/env python
from os.path import expanduser, islink, realpath

f="~/Library/LaunchAgents/org.lighttpd.plist"

path=expanduser(f)
print islink(path)
print open(path).read()

print realpath(path)