#!/usr/bin/env python

try:
    from urllib import quote
except ImportError:
    from urllib.parse import quote

url='file://localhost/Users/nordmenss/git/FIDDLE/css-fiddle/3DP/bootstrap/class="thumbnails".html'
print quote(url)