#!/usr/bin/env python
from threading import Thread

value=0
def count(*args):
    global value
    print args
    value+=1

t1 = Thread(target=count,args=(0,1,2))
t1.start()
t2 = Thread(target=count,args=(0,1,2))
t2.start()

print value