#!/usr/bin/env python
from os import popen
from dir import join

execfile(join("fixtures","output.py"))
# prints to stdout

execfile(join("fixtures","error.py"))
#popen("python "+join("fixtures","error.py"))