#!/usr/bin/env python
from jinja2 import Environment, PackageLoader
env = Environment(
    loader=PackageLoader('mypackage') # package_path='templates'
)
env = Environment(
    loader=PackageLoader('mypackage', 'views')
)
template = env.get_template('template.html')
template.render()

env = Environment(
    loader=PackageLoader('jinja.test')
)
template = env.get_template('template.html')
template.render()

