#!/usr/bin/env python
# http://docs.python.org/distutils/index.html

from distutils.core import find_packages,setup
setup(name='foo',
      package_dir = {'': 'src'},
      packages =find_packages()
)