#!/usr/bin/env python
from requests import get
from gitconfig import gitconfig

url="https://api.github.com/gists" 
r = get(url,auth=(gitconfig.user.name,gitconfig.github.password))

for l in r.json:
    print l
    print len(l.keys()),sorted(l.keys())
    # user updated_at user created_at public
