#!/usr/bin/env python
from requests import get
from gitconfig import gitconfig

url="https://api.github.com/orgs/%s" % "heroku"
r = get(url,auth=(gitconfig.user.name,gitconfig.github.password))
print r.json
print len(r.json.keys()),r.json.keys()
