#!/usr/bin/env python
from requests import get
from gitconfig import gitconfig

url="https://api.github.com/users/%s/received_events" % gitconfig.user.name
r = get(url,auth=(gitconfig.user.name,gitconfig.github.password))


for e in r.json:
    print e["payload"],e
    print len(e.keys()),e.keys()