#!/usr/bin/env python
from requests import get
from gitconfig import gitconfig

url="https://api.github.com/orgs/%s/events" % "casperjs"
r = get(url,auth=(gitconfig.user.name,gitconfig.github.password))

for l in r.json:
    print l
    print len(l.keys()),l.keys()
