#!/usr/bin/env python
from requests import get
from gitconfig import gitconfig

url="https://api.github.com/users/%s/events/orgs/%s" % \
("kennethreitz","heroku")
r = get(url,auth=(gitconfig.user.name,gitconfig.github.password))

print r.json
