#!/usr/bin/env python
from requests import get
from gitconfig import gitconfig

url="https://api.github.com/rate_limit"
r = get(url)
print r.json

r = get(url,auth=(gitconfig.user.name,gitconfig.github.password))
print r.json