#!/usr/bin/env python
from requests import get
from gitconfig import gitconfig

url="https://api.github.com/user/starred"
r = get(url,auth=(gitconfig.user.name,gitconfig.github.password))

for l in r.json:
    print l