#!/usr/bin/env python
from requests import get
from gitconfig import gitconfig

url="https://api.github.com/user/repos" 
r = get(url,auth=(gitconfig.user.name,gitconfig.github.password))

for r in r.json:
    print r
    print len(r.keys()),r.keys()
    # updated_at full_name owner id description fork
    # name language created_at private