#!/usr/bin/env python
from requests import get
from gitconfig import gitconfig

url="https://api.github.com/user" 
r = get(url,auth=(gitconfig.user.name,gitconfig.github.password))

print r.json
print r.json["email"]
print len(r.json.keys()),r.json.keys()
