#!/usr/bin/env python
from jinja2 import Environment

source="""
{% set total=0 %}
{% for i in range(5) %}
    {% set total=total+1 %}
    {{ total }}
{% endfor %}
{{ total }}
"""
env=Environment()
env.add_extension('jinja2.ext.do')
tmpl = env.from_string(source)
print tmpl.render()