#!/usr/bin/env python
from jinja2 import Environment
source="""
{% if var is none %}none{% else %}not none{% endif %}
{% if var2 is none %}none{% else %}not none{% endif %}
"""
tmpl = Environment().from_string(source)
print tmpl.render(var=None)