#!/usr/bin/env python
from jinja2 import Environment

source="""
{% if "1" in "123" %}
in
{% else %}
not in
{% endif %}
"""
tmpl = Environment().from_string(source)
print tmpl.render()

class cls:
    id=1
    value="123"

source="""
{% if "1" in item.value %}
in
{% else %}
not in
{% endif %}
"""
tmpl = Environment().from_string(source)
print tmpl.render(item=cls())