#!/usr/bin/env python
from jinja2 import Environment

source="""
{% if 1==1 %}if {% else %}else{% endif %}
{# and #}
{% if 1==1 and 2==2 %}if {% else %}else{% endif %}
{# elif #}
{% if True %}{% elif True %}{% else %}{% endif %}
"""
tmpl = Environment().from_string(source)
print tmpl.render()

source="""
{% if var is defined %}if{% else %}else{% endif %}
"""
tmpl = Environment().from_string(source)
print tmpl.render(var=0)