#!/usr/bin/env python
from jinja2 import Environment
source="""
{% if var is iterable %}
iterable
{% else %}
not iterable
{% endif %}
"""
tmpl = Environment().from_string(source)
print tmpl.render(var=[1,2,3])