#!/usr/bin/env python
from jinja2 import Environment
source="""
{% if var is number %}
number
{% else %}
not number
{% endif %}
"""
tmpl = Environment().from_string(source)
print tmpl.render(var=14.88)