#!/usr/bin/env python
from jinja2 import Environment
source="""
{% if var is callable %}
callable
{% else %}
not callable
{% endif %}
"""
tmpl = Environment().from_string(source)
print tmpl.render(var=lambda x:int(x))