#!/usr/bin/env python
from jinja2 import Environment

source="""
{% prepare "box" %}
<div id="box">this is the default box</div>
{% endprepare %}
{% call "box" %}
"""
tmpl = Environment().from_string(source)
print tmpl.render()