#!/usr/bin/env python
from pep8 import selftest, StyleGuide
arglist = [['statistics', True]]

pep8style = StyleGuide(config_file=True,paths=["test1.py"])
fail_s, done_s = selftest(pep8style.options)
print fail_s, done_s