#!/usr/bin/env python
from subprocess import PIPE, Popen

process = Popen("without_stderr",stdout=PIPE,shell=True)
stdout,stderr = process.communicate()

process = Popen("with_stderr",stderr=PIPE,stdout=PIPE,shell=True)
stdout,stderr = process.communicate()
