#!/usr/bin/env python

from re import findall, sub
process="com.apple.launchd.peruser.501[301] (org.lighttpd[88]) "
subprocess=findall("\(.*\)", process)[0][1:-1]
print subprocess
print sub("[\[\d\]]", "",subprocess)