#!/usr/bin/env python
from requests import get
from gitconfig import gitconfig

url="https://api.github.com/users/%s/events" % gitconfig.user.name
r = get(url,params={"page":1},auth=(gitconfig.user.name,gitconfig.github.password))

for l in r.json:
    print l
print len(r.json)

print "\n\n\n"
r = get(url,params={"page":2},auth=(gitconfig.user.name,gitconfig.github.password))

for l in r.json:
    print l