#!/usr/bin/env python
from requests import get
from gitconfig import gitconfig

url="https://api.github.com/users/cancerhermit/events/public"
r = get(url,auth=(gitconfig.user.name,gitconfig.github.password))

for e in r.json:
    print e