#!/usr/bin/env python
from datetime import datetime,time
print time()
print time(10,10,10)
print time(hour=12,minute=12,second=31,microsecond=0)
print time(10,10,10).hour
print time(hour=12,minute=None)

t=datetime.now().time()
print t,t.__class__