#!/usr/bin/env python
from requests import get

def staticurl(url):
    l=url.split("/")
    l.pop(len(l)-2)
    return "/".join(l)

r = get('https://api.github.com/gists/3889945')
print r.json
print r.json["files"]
print ""
for k,v in r.json["files"].iteritems():
    print k,v["raw_url"]
    print staticurl(v["raw_url"])
