#!/usr/bin/env python
from fluentxml import Parser
content=open('nosetests.xml').read()
xml = Parser(content)
print "root",xml.root
for a in ["failures","tests","errors","skip"]:
    print a,xml.root[a],
print ""