#!/usr/bin/env python
from fluentxml import Parser
content=open('nosetests.xml').read()
xml = Parser(content)
print xml
print "root",xml.root
for a in ["failures","tests","errors","skip"]:
    print a,xml.root[a],
print ""
print "testcase",xml.root.testcase # list
print "root",xml.root._children
for c in xml.root._children:
    print "c",c
    print c.skipped[0]._texts

#print "root",xml.root._texts
