#!/usr/bin/env python
from pep8 import StyleGuide


pep8style = StyleGuide(quiet=True)
r = pep8style.check_files(["test1.py"])
print r.__dict__
print r.error
print "total_errors",r.total_errors
print "file_errors",r.file_errors
print "line_offset",r.line_offset
print "lines",r.lines
print "messages",r.messages
print "filename",r.filename
print "elapsed",r.elapsed
print "_start_time",r._start_time
print "_benchmark_keys",r._benchmark_keys
print "expected",r.expected
print "counters",r.counters