#!/usr/bin/env python
from jinja2 import Environment

class cls:
    id=None
    value=None

    def __init__(self,id,value):
        self.id=id
        self.value=value

source="""
{% for i in items %}
    {{ i|attr("id") }} {{ i.id }}
{% endfor %}
"""
tmpl = Environment().from_string(source)
print tmpl.render(
    items=[cls(1,"v1"),cls(2,"v2"),cls(3,"v3")]
)