#!/usr/bin/env python
from jinja2 import Environment

# sum(iterable, attribute=None, start=0)

source="""
{{ items|sum }}
"""
tmpl = Environment().from_string(source)
items=[0,1,2,3]
print tmpl.render(
    items=items
)

class cls(object):
    value=None
    def __init__(self,value):
        self.value=value

source="""
{{ items|sum(attribute='value') }}
"""
tmpl = Environment().from_string(source)
print tmpl.render(
    items=[cls(1),cls(2),cls(3),cls(4)]
)